import type { Exercise } from "./domain";
import type { ExerciseGuide } from "./guides";
// Each variation has its own prescription, guide and motion configuration.
const entries: Array<
  [
    string,
    string,
    Exercise["muscle"],
    Exercise["equipment"],
    string,
    string,
    string[],
    string,
  ]
> = [
  [
    "sumo",
    "Dumbbell sumo squat",
    "Legs",
    "Dumbbells",
    "8–12",
    "Take a comfortable wide stance and hold one dumbbell at your chest.",
    [
      "Keep your knees following the direction of your toes.",
      "Lower between your feet while keeping the weight close.",
      "Press through your feet to return to standing.",
    ],
    "Avoid forcing an excessively wide stance or letting your knees collapse inward.",
  ],
  [
    "split",
    "Split squat",
    "Legs",
    "Bodyweight",
    "8–12 / side",
    "Stand in a staggered stance with your rear heel raised. Use nearby support if needed.",
    [
      "Bend both knees to lower straight down through a comfortable range.",
      "Keep your front foot planted and torso controlled.",
      "Push through your front foot to stand. Finish the reps, then switch sides.",
    ],
    "Avoid a tightrope stance or forcing your back knee to the floor.",
  ],
  [
    "lunge",
    "Reverse lunge",
    "Legs",
    "Bodyweight",
    "6–10 / side",
    "Stand tall with feet about hip-width apart.",
    [
      "Step one foot backward, keeping space between your feet.",
      "Bend both knees and lower only as far as you can balance.",
      "Push through the front foot to return. Alternate sides.",
    ],
    "Avoid stepping directly behind the other foot or rushing the return.",
  ],
  [
    "calf",
    "Standing calf raise",
    "Legs",
    "Bodyweight",
    "12–15",
    "Stand on a level floor with feet about hip-width apart. Use support for balance if needed.",
    [
      "Rise onto the balls of your feet without rolling your ankles outward.",
      "Pause briefly at the top.",
      "Lower your heels gently to the floor.",
    ],
    "Avoid bouncing or leaning forward to create momentum.",
  ],
  [
    "dbcalf",
    "Dumbbell calf raise",
    "Legs",
    "Dumbbells",
    "12–15",
    "Hold light dumbbells by your sides with feet about hip-width apart.",
    [
      "Keep your torso upright as you lift your heels.",
      "Balance on the balls of your feet briefly.",
      "Lower both heels slowly to the floor.",
    ],
    "Avoid using a load that makes you lose balance or bouncing through the reps.",
  ],
  [
    "goodmorning",
    "Bodyweight good morning",
    "Legs",
    "Bodyweight",
    "8–12",
    "Stand with knees relaxed and hands resting across your chest.",
    [
      "Move your hips backward while keeping your back steady.",
      "Let your torso tip forward until you feel a comfortable hamstring stretch.",
      "Bring your hips forward to stand without leaning backward.",
    ],
    "Avoid rounding your back or chasing a deeper range.",
  ],
  [
    "bentrow",
    "Bent-over dumbbell row",
    "Back",
    "Dumbbells",
    "8–12",
    "Hold two dumbbells and hinge forward with knees softly bent.",
    [
      "Keep your torso steady and let both weights hang.",
      "Draw your elbows back toward your hips.",
      "Lower the weights slowly without changing your trunk position.",
    ],
    "Avoid jerking your torso upward or shrugging to complete the pull.",
  ],
  [
    "reversefly",
    "Dumbbell reverse fly",
    "Shoulders",
    "Dumbbells",
    "10–15",
    "Hinge forward with light dumbbells hanging beneath your shoulders.",
    [
      "Keep a small, steady bend in your elbows.",
      "Raise your arms out to the sides through a comfortable range.",
      "Lower slowly while keeping your torso still.",
    ],
    "Avoid swinging, shrugging, or lifting above your shoulder line.",
  ],
  [
    "lateral",
    "Dumbbell lateral raise",
    "Shoulders",
    "Dumbbells",
    "10–15",
    "Stand tall with light dumbbells by your sides and elbows slightly bent.",
    [
      "Raise both arms out to the sides, slightly forward of your torso.",
      "Stop at or below shoulder height.",
      "Lower slowly without changing the bend in your elbows.",
    ],
    "Avoid throwing the weights upward or shrugging your shoulders.",
  ],
  [
    "frontraise",
    "Dumbbell front raise",
    "Shoulders",
    "Dumbbells",
    "10–12",
    "Stand with light dumbbells in front of your thighs and knees relaxed.",
    [
      "Keep your trunk steady and a soft bend in your elbows.",
      "Lift the weights in front of you to a comfortable height no higher than your shoulders.",
      "Lower slowly to the starting position.",
    ],
    "Avoid leaning backward or swinging to start the lift.",
  ],
  [
    "hammer",
    "Dumbbell hammer curl",
    "Arms",
    "Dumbbells",
    "10–12",
    "Hold dumbbells at your sides with palms facing each other.",
    [
      "Keep your upper arms close to your body.",
      "Bend your elbows to raise the weights while keeping your palms inward.",
      "Lower slowly without swinging your torso.",
    ],
    "Avoid bending your wrists or driving your elbows forward.",
  ],
  [
    "altcurl",
    "Alternating dumbbell curl",
    "Arms",
    "Dumbbells",
    "8–12 / side",
    "Stand with dumbbells at your sides, palms forward.",
    [
      "Curl one weight while keeping that upper arm steady.",
      "Lower it slowly to your side.",
      "Repeat with the other arm, counting reps per side.",
    ],
    "Avoid rotating your torso or swinging the resting weight.",
  ],
  [
    "seatedpress",
    "Seated dumbbell shoulder press",
    "Shoulders",
    "Dumbbells",
    "8–12",
    "Sit on a stable bench with feet planted and dumbbells at shoulder height.",
    [
      "Keep your ribs over your pelvis.",
      "Press the weights overhead through a comfortable range.",
      "Lower slowly to shoulder height.",
    ],
    "Avoid arching your lower back or bouncing the weights.",
  ],
  [
    "closefloor",
    "Close-grip dumbbell floor press",
    "Chest",
    "Dumbbells",
    "8–12",
    "Lie on your back with knees bent. Hold dumbbells with palms facing each other.",
    [
      "Keep your elbows nearer your sides as you lower.",
      "Let your upper arms meet the floor gently.",
      "Press upward without bouncing or forcing your wrists together.",
    ],
    "Avoid flaring your elbows or letting your wrists fold back.",
  ],
  [
    "deadbug",
    "Dead bug",
    "Core",
    "Bodyweight",
    "6–10 / side",
    "Lie on your back with arms pointing upward and hips and knees bent.",
    [
      "Gently brace your abdomen.",
      "Slowly reach one arm overhead and extend the opposite leg, stopping before your back arches.",
      "Return to the start and alternate sides.",
    ],
    "Avoid lowering farther than you can control or holding your breath.",
  ],
  [
    "donkey",
    "Quadruped hip extension",
    "Legs",
    "Bodyweight",
    "8–12 / side",
    "Start on hands and knees with your trunk steady.",
    [
      "Keep one knee bent as you lift that thigh behind you.",
      "Stop before your lower back arches or your hips rotate.",
      "Return the knee under your hip. Complete the planned reps on each side.",
    ],
    "Avoid throwing the leg upward or shifting all your weight sideways.",
  ],
  [
    "hydrant",
    "Fire hydrant",
    "Legs",
    "Bodyweight",
    "8–12 / side",
    "Start on hands and knees, with your abdomen gently braced.",
    [
      "Keep one knee bent as you lift that thigh out to the side.",
      "Use a small range that allows your hips to stay level.",
      "Return slowly and complete the planned reps on each side.",
    ],
    "Avoid twisting your chest or rolling your pelvis open.",
  ],
  [
    "narrowpushup",
    "Close-hand incline push-up",
    "Chest",
    "Bodyweight",
    "6–10",
    "Place your hands slightly narrower than shoulder width on a sturdy bench.",
    [
      "Step back and keep your body in a straight line.",
      "Lower your chest toward the bench with elbows close to your torso.",
      "Press away while keeping your trunk steady.",
    ],
    "Avoid using an unstable surface or letting your hips sag.",
  ],
];
export const extraExercises: Exercise[] = entries.map(
  ([id, name, muscle, equipment, reps, setup, steps]) => ({
    id,
    name,
    muscle,
    equipment,
    reps,
    cue: steps[1],
  }),
);
export const extraGuides: Record<string, ExerciseGuide> = Object.fromEntries(
  entries.map(([id, , , , , setup, steps, avoid]) => [
    id,
    {
      setup,
      steps,
      avoid,
      breathing: ["deadbug", "donkey", "hydrant"].includes(id)
        ? "Breathe steadily throughout; breathe out as you extend or lift."
        : "Breathe out through the lifting effort and in as you return with control.",
    },
  ]),
);
